--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.1.22.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 6/5/2022 11:30:13 PM
-- Server version: 5.5.5-10.4.24-MariaDB
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO ilisi1_atelier1_gestion_stages.admin(id) VALUES
(13);


INSERT INTO ilisi1_atelier1_gestion_stages.candidature(id, created_date, status, updated_date, etudiant_id, offre_id, `position`) VALUES
(1, '2022-06-02 20:25:20', 'APPLIED', '2022-06-02 20:25:20', 9, 2, NULL);




INSERT INTO ilisi1_atelier1_gestion_stages.enseignant(id) VALUES
(6),
(14),
(15);


INSERT INTO ilisi1_atelier1_gestion_stages.entreprise(id, domaine, email, logo, short_name, name, phone, web_site, description) VALUES
(1, 'IT', 'Involys@test.com', 'jsPQVvABFF-Involys.png', 'Involys', 'Involys entreprise', '06586584252', 'Involys.com', 'this is a random entreprise in IT'),
(2, 'Corrupti voluptatem sed nihil.', 'your.email+fakedata98995@gmail.com', NULL, '', 'Deondre Wehner', '', '', ''),
(3, 'Dolorem aut voluptatem eligendi vero.', 'your.email+fakedata60477@gmail.com', NULL, 'Courtney McDerm', 'Pink Rogahn', '387-883-1918', 'Missouri', 'Eos praesentium rerum ipsa consequatur inventore assumenda occaecati architecto.'),
(4, 'Dolorem aut voluptatem eligendi vero.', 'your.email+fakedata60477@gmail.com', NULL, 'Courtney McDerm', 'Pink Rogahn', '387-883-1918', 'Missouri', 'Eos praesentium rerum ipsa consequatur inventore assumenda occaecati architecto.'),
(19, 'Laudantium ut aut dicta perspiciatis vel ipsa quae', 'your.email+fakedata72521@gmail.com', 'wP4L2y0CT1-LabVantage.jpg', 'Helene Ortiz', 'Chesley Torp', '760-044-5052', 'South Dakota', 'Natus incidunt exercitationem cupiditate perferendis sed delectus.'),
(20, 'Laudantium ut aut dicta perspiciatis vel ipsa quae', 'your.email+fakedata72521@gmail.com', 'mkzDwZLttp-LabVantage.jpg', 'Helene Ortiz', 'Chesley Torp', '760-044-5052', 'South Dakota', 'Natus incidunt exercitationem cupiditate perferendis sed delectus.'),
(21, 'Dolorem illo consequatur a iste accusantium minus ', 'your.email+fakedata82965@gmail.com', 'rYIzxrIET0-800px-ALTEN_logo.svg.png', 'Lon Kris', 'Christian O''Keefe', '480-838-5618', 'Connecticut', 'Incidunt quia corrupti tenetur eum unde repudiandae.');


INSERT INTO ilisi1_atelier1_gestion_stages.etudiant(cne, cv, promotion, id, formation_id, IsValidated) VALUES
('526-016-1684', '0lx0uWbJPC-PMP Biopharned.pdf', 613, 9, 1, 1),
('055-157-1450', NULL, 2021, 10, 1, 0),
('799-942-2995', NULL, 2021, 12, 1, 0);


INSERT INTO ilisi1_atelier1_gestion_stages.formation(id, short_title, title, type, responsable_id) VALUES
(1, 'ilisi', 'integration des sys', 'FI', 6),
(5, 'gmi', 'Regional Operations Agent', 'FI', 15);



INSERT INTO ilisi1_atelier1_gestion_stages.offre(id, created_date, delai_offre, description, duree_stage, end_stage, nbr_stagiaire, start_stage, statue, title, type_stage, updated_date, entreprise_id, formation_id) VALUES
(1, '2022-05-11 00:00:00', '2022-05-12', 'Molestias minima aspernatur qui aut aliquam distinctio officia quia.', 445, '2022-05-05', 5, '2022-05-11', 'NEW', 'Veritatis et est laboriosam.', 'PFE', '2022-05-12 00:00:00', 1, 1),
(2, '0000-00-00 00:00:00', '2022-07-10', 'Aut nisi aliquid dolores unde alias accusamus animi.', 604, '2021-10-27', 5, '2022-11-18', 'NEW', 'Investor Solutions Associate', 'PFE', '2022-06-01 20:31:07', 4, 1),
(3, '2022-05-30 12:25:02', '2021-06-08', 'Qui dolorem aut quas non ut dolore facilis sint.', 461, '2022-09-01', 255, '2022-10-07', 'CLOSED', 'Dynamic Tactics Producer', 'INIT', '2022-05-30 12:25:02', 2, 1),
(4, '2022-06-04 14:23:28', '2023-04-30', 'Itaque quas ratione amet itaque voluptatum.', 259, '2022-07-27', 255, '2022-05-19', 'NEW', 'Investor Interactions Supervisor', 'PFA', '2022-06-04 14:23:28', 20, 1),
(5, '2022-06-04 14:23:48', '2023-05-23', 'Molestiae aperiam distinctio voluptatibus consequatur adipisci est est.', 321, '2022-09-10', 255, '2023-05-15', 'FULL', 'Senior Accounts Administrator', 'SUMMER', '2022-06-04 14:23:48', 3, 1);


INSERT INTO ilisi1_atelier1_gestion_stages.person(id, cin, date_naiss, email, fname, lname, password, phone, person_type, profile_img) VALUES
(6, 'C4582562', '2022-05-05 00:00:00', 'responsable@test.com', 'test name', 'test lname', 'password', '062548515', 'enseignant', 'iwv4TUwB1U-image.gif'),
(9, 'Lake Kathryn', '2022-06-12 00:00:00', 'test@test.com', 'Eusebio Howe', 'Frida Gutmann', 'password', '500-811-7899', 'etudiant', 'Pu3RAUsLKg-istya group.jpeg'),
(10, 'Christafurt', '2022-02-15 00:00:00', 'your.email+fakedata73288@gmail.com', 'Cora Beier', 'Maya Gleason', 'RsyiMTReBCQfpeg', '065-907-0059', 'etudiant', NULL),
(11, 'North Chelseabo', '2023-01-29 00:00:00', 'test123@gmail.com', 'Antwon Wolf', 'Arno Rowe', 'test123', '960-206-7465', 'etudiant', NULL),
(12, 'Port Eliseoside', '2022-11-07 00:00:00', 'test@gmail.com', 'Jocelyn Batz', 'Ruthie Medhurst', 'password', '626-366-6311', 'etudiant', NULL),
(13, 'Metastad', '2023-02-19 00:00:00', 'admin@test.com', 'Maurice Bailey', 'Josiah Lebsack', 'password', '060-526-8261', 'etudiant', NULL),
(14, 'Champlinberg', '2022-07-21 00:00:00', 'gmi_resp@test.com', 'Vicente Orn', 'Dario Auer', 'Champlinberg', '157-642-8171', 'enseignant', NULL),
(15, 'New ddd', '2023-05-11 00:00:00', 'resp2@gmail.com', 'Jennie Dibbert', 'Josie Dach', 'New ddd', '642-937-3847', 'enseignant', NULL);


INSERT INTO ilisi1_atelier1_gestion_stages.stage(id, description, end, start, statue, created_date, updated_date, entreprise_id, stagiaire_id, encardant_note, encadrant_ext_note, encadrant_id, candidature_id) VALUES
(1, '5dcds545sd445sd s54sd5 ss5ff', '2022-06-15', '2022-06-10', 'DRAFT', '2022-06-05 20:46:06', '2022-06-05 20:46:06', 3, 9, 0, 0, 6, NULL);

